-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.houses
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title text COLLATE pg_catalog."default",
    slug text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    description text COLLATE pg_catalog."default",
    hidden boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT houses_pkey PRIMARY KEY (id, slug),
    CONSTRAINT houses_id_key UNIQUE (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.houses
    OWNER to postgres;

ALTER TABLE IF EXISTS public.houses
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.houses TO anon;

GRANT ALL ON TABLE public.houses TO authenticated;

GRANT ALL ON TABLE public.houses TO postgres;

GRANT ALL ON TABLE public.houses TO service_role;
CREATE POLICY "Enable insert for authenticated users only"
    ON public.houses
    AS PERMISSIVE
    FOR INSERT
    TO authenticated
    WITH CHECK (true);
CREATE POLICY "Enable read access for all users"
    ON public.houses
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);

ALTER TABLE IF EXISTS public.rounds
    ADD COLUMN "houseId" bigint;
ALTER TABLE IF EXISTS public.rounds
    ADD CONSTRAINT "rounds_houseId_fkey" FOREIGN KEY ("houseId")
    REFERENCES public.houses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
